---
- name: CI/CD Rules
  hosts: all
  sources:
    - name: azure_service_bus
      azure_service_bus:
        conn_str: "{{connection_str}}"
        queue_name: "{{queue_name}}"
  rules:
    - name: extract values
      condition: event.payload.repository.full_name == "benthomasson/simple-app"
      action:
        post_event:
          fact:
            repository_name: "{{event.payload.repository.full_name}}"
            repository_url: "{{event.payload.repository.clone_url}}"
            after: "{{event.payload.after}}"
    - name: run tests
      condition: event.repository_name == "benthomasson/simple-app"
      action:
        run_playbook:
          name: run_simple_app_test.yml
          post_events: true
    - name: print output
      condition: event.output is defined
      action:
        print_event:
          var_root: output
    - name: print error
      condition: event.error is defined
      action:
        print_event:
          var_root: error
...
