---
- name: Test that wrong source fails
  hosts: all
  sources:
    - ansible.eda.idonotexist:
        limit: 6
  rules:
    - name: Debug
      condition: event.i == 2
      action:
        debug:
          msg: "debug me"

